#164489878 set up empty react project
andela/bad_ass-ah-frontend pull request #2
Opened 2019-05-13 13:31 UTC by Jaman-dedy

**What this PR do?**

This PR will set up an empty react project

**How should this be manually tested?**
_  this can be manually tested by running the following command `npm start`

**What are the relevant pivotal tracker stories?**
[#164489878](https://www.pivotaltracker.com/story/show/164489878)

2019-05-13 13:43 UTC, blaisebakundukize commented
Good job @Jaman-dedy, I appreciate the task you. But you have to add a new line at the end of ```.gitignore``` file. Thx

2019-05-13 13:46 UTC, zellymiriam commented on src/App.js
> +function App() {
Please use  Es6

2019-05-13 13:52 UTC, Paccy10 reviewed
Nice job @Jaman-dedy , but I think you have to name the `allreducers.js`  file as `index.js`

2019-05-13 14:04 UTC, zellymiriam commented on src/reducers/allreducers.js
> +console.log('hello');
remove console.log

2019-05-13 14:04 UTC, zellymiriam commented on src/components/layouts/navbar.js
> +console.log('hello');
remove console.log

2019-05-13 14:05 UTC, zellymiriam commented on src/actions/user.js
> +console.log('hello');
remove console.log

2019-05-13 14:13 UTC, nakiwuge requested changes
@Jaman-dedy nice job, however, everything to do with actions and reducers should not be in this pull request because that is redux please remove them.
 Also, your commit message has no body please add a body and attend to the other comments I have left on this PR

2019-05-13 14:15 UTC, zellymiriam commented on src/serviceWorker.js
> +// This optional code is used to register a service worker.
Remove this file as we won't need it for this project. Read when serviceWorker is used  for your own information

2019-05-14 08:06 UTC, nakiwuge approved these changes

2019-05-14 08:06 UTC, merged