Feature(reading stats): user reading stats
andela/bad_ass-ah-frontend pull request #27
Opened 2019-06-09 11:41 UTC by blaisebakundukize

- set users reading stats when they read an article
- get user reading stats

[Delivers #164489909]

**What does this PR do?**

This PR set and get user reading stats

**Description of Task to be completed?**

setting users reading stats happens when they read an article, and for getting them they have to view their profile.

**How should this be manually tested?**

- Login to application
- read an article to set your reading stats
- visit your profile to view your total reading stats

**What are the relevant pivotal tracker stories?**

[#164489909](https://www.pivotaltracker.com/story/show/164489909)

**Screenshots (if appropriate)**

xxx

2019-06-10 13:22 UTC, zellymiriam commented on src/components/articles/SingleArticle.js
> +    } = this.state;
Add empty line

2019-06-10 13:23 UTC, zellymiriam commented on src/components/articles/SingleArticle.js
> +    if (article !== null) if (article && article.article !== undefined) single = article.article;
Add new line before this line

2019-06-10 13:24 UTC, zellymiriam commented on src/components/users/profile/ViewProfile.js
> +    if (errorGetReadingStats === null && readingStats > 0) {
Add new line before this line

2019-06-10 13:27 UTC, nakiwuge requested changes
@blaisebakundukize good job on the implementation however for greater user experience add a hover effect with `Read articles` on the icon you used for reading.

Also, check out the comments I left on the PR.

2019-06-10 14:10 UTC, blaisebakundukize commented
> @blaisebakundukize good job on the implementation however for greater user experience add a hover effect with `Read articles` on the icon you used for reading.
> 
> Also, check out the comments I left on the PR.

2019-06-11 14:34 UTC, nakiwuge approved these changes

2019-06-11 14:50 UTC, merged